version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: prod
      APP_APP_NAME: fastapi-min
      APP_DEBUG: "false"
  nginx:
    image: nginx:alpine
    depends_on: [web]
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  prometheus:
    image: prom/prometheus:latest
    depends_on: [web]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana-oss:latest
    depends_on: [prometheus]
    ports:
      - "3000:3000"
  alertmanager:
    image: prom/alertmanager:latest
    depends_on: [prometheus]
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro


