# Tempo 配置文件
# 用于分布式追踪

server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    # OTLP gRPC
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    
    # Jaeger
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
    
    # Zipkin
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    
    wal:
      path: /var/tempo/wal
    
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  max_concurrent_queries: 20
  frontend_worker:
    frontend_address: localhost:9095

query_frontend:
  search:
    max_duration: 0s

metrics_generator:
  # 指标生成器配置
  registry:
    external_labels:
      source: tempo
      cluster: demo-cluster
  
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  
  # 生成的指标
  processor:
    service_graphs:
      enabled: true
      max_items: 10000
    
    span_metrics:
      enabled: true
      dimensions:
        - name: http.method
        - name: http.status_code
        - name: service.name

overrides:
  defaults:
    metrics_generator:
      processors: ['service-graphs', 'span-metrics']

